name: vscode_runner
description: KRunner plugin for quickly opening recent VSCode workspaces
version: 1.6.1
publish_to: none
homepage: https://github.com/Merrit/vscode-runner
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  krunner: ^0.2.0
  logger: ^2.0.2+1
  sqlite3: ^1.5.1
  xdg_directories: ^1.0.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.0
