name: vscode_runner
description: KRunner plugin for quickly opening recent VSCode workspaces
version: 1.8.0
publish_to: none
homepage: https://github.com/Merrit/vscode-runner
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  krunner: ^1.0.1
  logger: ^2.0.2+1
  sqlite3: ^2.4.6
  xdg_desktop_portal: ^0.1.13
  xdg_directories: ^1.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
