# Verify tests pass and builds succeed for pull requests.

name: Verify Pull Request

on:
  # Enable manual run
  workflow_dispatch:
  pull_request:

concurrency:
  group: ci-verify-pr-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
#   call-tests:
#     uses: ./.github/workflows/tests.yml

  call-build:
    # needs: call-tests
    uses: ./.github/workflows/build.yml
    with:
      pre-release: true
    secrets: inherit

  verify-pull-request:
    name: Verify Pull Request
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Requirements passed, PR looks good!"
